apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: api-gateway-image
    newName: gitea.healthcare.com/KLTN/api-gateway
    newTag: latest
