apiVersion: v1
kind: Service
metadata:
  name: healthcare-identity
  labels:
    app: healthcare-identity
spec:
  selector:
    app: healthcare-identity
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
