apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base manifests
resources:
  - ../../../base/frontend

# Add prefix to resources for environment isolation
namePrefix: staging-
namespace: staging

images:
  - name: gitea.kltn.internal/kltn/healthcare-frontend
    newName: gitea.kltn.internal:80/kltn/healthcare-frontend
    newTag: "14"

# Apply the patches
patches:
  - path: service-patch.yaml
