apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-frontend
  template:
    metadata:
      labels:
        app: healthcare-frontend
    spec:
      containers:
        - name: healthcare-frontend
          image: healthcare-frontend-image:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: healthcare-app-secret
      imagePullSecrets:
        - name: gitea-registry-secret
