apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/auth-service
namespace: production
images:
  - name: gitea.healthcare.com/KLTN/healthcare-auth
    newTag: "latest"
