apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: healthcare-backend-image
    newName: gitea.healthcare.com/KLTN/healthcare-backend
    newTag: latest
