apiVersion: v1
kind: Service
metadata:
  name: healthcare-appointment
spec:
  selector:
    app: healthcare-appointment
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
