apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthcare-global-secret-prod
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: healthcare-global-secret-prod
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secrets-prod
