apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthcare-global-secrets-pro
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: healthcare-global-secrets-pro
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secrets-prod
