apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - global-externalsecret.yaml
  - admin-service
  - auth-service
  - backend-service
  - frontend
  - http-route.yaml

patches:
  - target:
      kind: Deployment
      name: healthcare-identity
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
  - target:
      kind: Deployment
      name: healthcare-appointment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
  - target:
      kind: Deployment
      name: healthcare-admin
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
  - target:
      kind: Deployment
      name: healthcare-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-admin-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-admin-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-identity-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-identity-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-appointment-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-appointment-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-frontend-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-frontend-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
