apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - global-externalsecret.yaml
  - admin-service
  - identity-service
  - appointment-service
  - frontend
  - http-route.yaml
  - ../../../databases/overlays/identity-db
  - ../../../databases/overlays/admin-db
  - ../../../databases/overlays/appointment-db

patches:
  - target:
      kind: Deployment
      name: healthcare-identity
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: healthcare-global-secret-prod
                key: DATABASE_URL_IDENTITY
  - target:
      kind: Deployment
      name: healthcare-appointment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: healthcare-global-secret-prod
                key: DATABASE_URL_APPOINTMENT
          - name: IDENTITY_SERVICE_URL
            value: "http://healthcare-identity"
          - name: ADMIN_SERVICE_URL
            value: "http://healthcare-admin"
          - name: APPOINTMENT_SERVICE_URL
            value: "http://healthcare-appointment"
  - target:
      kind: Deployment
      name: healthcare-admin
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: healthcare-global-secret-prod
                key: DATABASE_URL_ADMIN
          - name: IDENTITY_SERVICE_URL
            value: "http://healthcare-identity"
          - name: ADMIN_SERVICE_URL
            value: "http://healthcare-admin"
          - name: APPOINTMENT_SERVICE_URL
            value: "http://healthcare-appointment"

  - target:
      kind: Deployment
      name: healthcare-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-prod
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-admin-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-admin-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-identity-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-identity-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-appointment-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-appointment-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: healthcare-frontend-hpa
    patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: healthcare-frontend-hpa
      spec:
        minReplicas: 2
        maxReplicas: 5
