apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/identity-service
namespace: staging
images:
  - name: gitea.healthcare.com/kltn/healthcare-identity
    newTag: "d613fae8"

patches:
  - target:
      kind: Deployment
      name: healthcare-identity
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-dev
  - target:
      kind: Deployment
      name: healthcare-identity
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 75m
            memory: 96Mi
          limits:
            cpu: 200m
            memory: 192Mi
