apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:          # BẮT BUỘC sửa chữ 'd' thành 'D' viết hoa ở đây
            name: aws-academy-creds
            key: access-key-id
          secretAccessKeySecretRef:      # Trường này viết thường bình thường
            name: aws-academy-creds
            key: secret-access-key
          sessionTokenSecretRef:         # Trường này viết thường bình thường
            name: aws-academy-creds
            key: session-token