apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - overlays/auth-db
  - overlays/payment-db
  - overlays/appointment-db
  - overlays/medical-record-db
  - overlays/clinic-db