apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - healthcare-frontend-staging.yaml
  - healthcare-backend-staging.yaml
  - healthcare-auth-staging.yaml
  - healthcare-admin-staging.yaml
