apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitea.kltn.internal/KLTN/healthcare-manifests.git' # Thay bằng URL repo Gitea/GitHub thật của bạn
    targetRevision: main
    path: infrastructure/external-secrets # Trỏ thẳng vào thư mục vừa tạo ở trên
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true