apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana-community.github.io/helm-charts"
    chart: grafana
    targetRevision: "12.4.2"
    helm:
      releaseName: grafana
      values: |
        adminUser: admin
        adminPassword: admin123
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.10.235
        persistence:
          enabled: true
          size: 10Gi
          storageClass: longhorn
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
              # - name: Loki
              #   type: loki
              #   url: http://loki.monitoring.svc.cluster.local:3100
              #   isDefault: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - PruneLast=true
