apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-apps-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitea.healthcare.com/KLTN/healthcare-manifests.git'
    targetRevision: main
    path: apps/overlays/staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipSchemaValidation=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m