apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-apps-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitea.healthcare.com/KLTN/healthcare-manifests.git'
    targetRevision: main   
    path: apps/overlays/production
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipSchemaValidation=true
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m