apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-apps-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitea.healthcare.com/KLTN/healthcare-manifests.git'
    targetRevision: main 
    path: apps/overlays/staging 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: staging 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - ServerSideApply=true 