apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitea.healthcare.com/KLTN/healthcare-manifests.git'
    targetRevision: main
    path: infrastructure/longhorn
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/ports/0/nodePort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
