apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthcare-db
namePrefix: admin-db-
commonLabels:
  app: admin-db-postgres
resources:
  - ../../base
patches:
  - path: patch-env.yaml
