apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-identity
  labels:
    app: healthcare-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-identity
  template:
    metadata:
      labels:
        app: healthcare-identity
    spec:
      containers:
        - name: healthcare-identity
          image: healthcare-identity-image:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: healthcare-app-secret
      imagePullSecrets:
        - name: gitea-registry-secret
