apiVersion: v1
kind: Service
metadata:
  name: healthcare-admin
  labels:
    app: healthcare-admin
spec:
  selector:
    app: healthcare-admin
  ports:
    - name: http
      port: 80
      targetPort: 3002
      protocol: TCP
  type: ClusterIP
