apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend-service
namespace: staging
images:
  - name: gitea.kltn.internal:80/kltn/healthcare-backend
    newTag: "0145e0f5"

patches:
  - target:
      kind: Deployment
      name: healthcare-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-dev
