apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend-service
namespace: staging
images:
  - name: gitea.healthcare.com/kltn/healthcare-appointment
    newTag: "38c6a45b"

patches:
  - target:
      kind: Deployment
      name: healthcare-appointment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: healthcare-global-secret-dev
  - target:
      kind: Deployment
      name: healthcare-appointment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 150m
            memory: 192Mi
          limits:
            cpu: 400m
            memory: 384Mi
