apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-appointment
  labels:
    app: healthcare-appointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-appointment
  template:
    metadata:
      labels:
        app: healthcare-appointment
    spec:
      containers:
        - name: healthcare-appointment
          image: healthcare-appointment-image:latest
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
      imagePullSecrets:
        - name: gitea-registry-secret
