apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthcare-global-secret-dev
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: SecretStore
  target:
    name: healthcare-global-secret-dev
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secrets-dev
